---
- hosts: all
  gather_facts: false

  vars:
    server_list:
      - server_name: ubuntu.lab.com
        account:
          - account_name: account1
            account_action: revoke

  tasks:
  - name: Collect account information
    shell: 'cut -d: -f1 /etc/passwd'
    register: accounts_list

  - set_fact:
      userslist: "{{ accounts_list }}"

  - name: Confirm account exists
    debug:
      msg: "Account {{ item.1.account_name }} doesn't exist on {{ inventory_hostname }}"
    when:
      - item.1.account_name not in userslist.stdout
      - inventory_hostname==item.0.server_name
    with_subelements:
      - "{{ server_list }}"
      - account
    ignore_errors: yes

  - name: Terminating account SSH session and processes
    command: pkill -u "{{ item.1.account_name }}"
    when:
      - item.1.account_name in userslist.stdout
      - inventory_hostname==item.0.server_name
    with_subelements:
      - "{{ server_list }}"
      - account
    ignore_errors: yes
    failed_when: false

  - name: Lock account login
    user:
      name: "{{ item.1.account_name }}"
      shell: /sbin/nologin
    when:
      - item.1.account_name in userslist.stdout
      - item.1.account_action | lower == 'lock'
      - inventory_hostname==item.0.server_name
    with_subelements:
      - "{{ server_list }}"
      - account
    ignore_errors: true

  - name: Lock account password
    command: passwd -l "{{ item.1.account_name }}"
    when:
      - item.1.account_name in userslist.stdout
      - item.1.account_action | lower == 'lock'
      - inventory_hostname==item.0.server_name
    with_subelements:
      - "{{ server_list }}"
      - account
    ignore_errors: true

  - name: Clear failed logins and unlock account
    shell: |
       pam_tally2 --user "{{ item.1.account_name }}" --reset
       passwd -u "{{ item.1.account_name }}"
    when:
      - item.1.account_name in userslist.stdout
      - item.1.account_action | lower == 'unlock'
      - inventory_hostname==item.0.server_name
    with_subelements:
      - "{{ server_list }}"
      - account
    ignore_errors: true

  - name: Revoke account
    user:
      name: "{{ item.1.account_name }}"
      state: absent
      remove: yes
    when:
      - item.1.account_action | lower == 'revoke'
    with_subelements:
      - "{{ server_list }}"
      - account
